config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  resources :users, only: [:new, :create, :show]

  resources :orders, only: [:index, :show, :create, :update]

  resource :dashboard, only: [:show]

  namespace :admin do
    resource :dashboard, only: [:show]
    resource :user, only: [:edit, :update]
    get 'orders/ordered', to: 'orders#index'
    get 'orders/paid', to: 'orders#index'
    get 'orders/cancelled', to: 'orders#index'
    get 'orders/completed', to: 'orders#index'
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :item do
    resources :reviews, only: [:create, :destroy]
  end

  resources :items, only: [:index, :show, :new, :create]
  put '/cart', to: 'carts#edit'
  post '/cart', to: 'carts#create'
  get '/cart', to: 'carts#index'
  delete '/cart', to: "carts#destroy"
  get '/:category', to: 'categories#show', as: :category
end

app/views/shared/_item_show.html.erb
<h2><%= item.title %></h2>
<h4><%= item.description %></h4>
<h5>Price: <%= number_to_currency(item.dollars) %></h5>

app/views/shared/_navigation.html.erb
<div class="container">
    <ul class="nav nav-tabs">

      <li role="presentation"><%= link_to "Waddams Emporium", items_path, class: "navbar-nav-item nav-link" %></li>

      <% if current_admin?  %>

        <li role="presentation"><%= link_to "Welcome, Administrator...", admin_dashboard_path, class: "nav-item nav-link" %></li>
        <li role="presentation"><%= link_to "Orders", orders_path, class: "nav-item nav-link" %></li>
        <li role="presentation"><%= link_to "Logout", logout_path, method: :delete, class: "nav-item nav-link"%></li>

      <% elsif logged_in? %>

        <li role="presentation"><%= link_to "Welcome, #{current_user.username}...", dashboard_path, class: "nav-item nav-link" %></li>
        <li role="presentation"><%= link_to "Orders", orders_path, class: "nav-item nav-link" %></li>
        <li role="presentation"><%= link_to "Logout", logout_path, method: :delete, class: "nav-item nav-link"%></li>

      <% else %>

        <li role="presentation"><%= link_to "Login", login_path, class: "nav-item nav-link"%></li>
        <li role="presentation"><%= link_to "Create Account", new_user_path, class: "nav-item nav-link"%></li>

      <% end %>

      <% if !cart_empty? %>

        <li role="presentation"><%= link_to "Cart", cart_path, class: "nav-item nav-link" %></li>

      <% end %>
    </ul>
</div>

app/views/shared/_review_index.html.erb
<div class="reviews container">
  <h3>Reviews</h3>
  <% item.reviews.each do |review| %>
    <div class="review panel panel-default">
      <div class="panel-body">
        <h4> <%= review.body %> </h4>
        <p> Posted by <%= review.user.username %> </p>
        <p> Posted on <%= review.created_at %> </p>
        <div class="stars">
          <% review.stars.times do %>
            <span class="glyphicon glyphicon-star"></span>
          <% end %>
          <% (5 - review.stars).times do %>
            <span class="glyphicon glyphicon-star-empty"></span>
          <% end %>
          <% if review.user == current_user %>
            <%= button_to "Delete Review", item_review_path(review), method: :delete %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_review_new.html.erb
<% if logged_in? %>
  <div class="container">
    <div class="panel panel-default">

      <div class="panel-heading">
        <h3 class="panel-title">Submit a new review for: <%= item.title %></h3>
      </div>

      <div class="new_review panel-body">

        <%= form_for [item, review], :html => {:class => "form"} do |f| %>
          <%= f.hidden_field :item_id, value: item.id %>
          <div class="container">

            <div class="col-md-11">
              <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, class: "form-control" %>
              </div>
            </div>

            <div class="col-md-3">
              <div class="form-group">
                <%= f.label :stars %>
                <%= select_tag :stars, options_for_select([1, 2, 3, 4, 5]), class: "form-control" %>
              </div>
            </div>

          </div>

          <div class="container">
            <div class="col-md-3">
              <%= f.submit "Submit Review", class: "btn btn-primary" %>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  <% end %>
</div>