config/routes.rb
Rails.application.routes.draw do

  root 'items#index'

  resources :users, only: [:new, :create, :show]

  resources :orders, only: [:index, :show, :create, :update]

  resource :dashboard, only: [:show]

  namespace :admin do
    resource :dashboard, only: [:show]
    resource :user, only: [:edit, :update]
    get 'orders/ordered', to: 'orders#index'
    get 'orders/paid', to: 'orders#index'
    get 'orders/cancelled', to: 'orders#index'
    get 'orders/completed', to: 'orders#index'
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :item do
    resources :reviews, only: [:create, :destroy]
  end

  resources :items, only: [:index, :show, :new, :create]
  put '/cart', to: 'carts#edit'
  post '/cart', to: 'carts#create'
  get '/cart', to: 'carts#index'
  delete '/cart', to: "carts#destroy"
  get '/:category', to: 'categories#show', as: :category
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < Admin::BaseController
  helper_method :can_be_cancelled?

  def show
    @user = current_user
    @orders = Order.all
  end

  def can_be_cancelled?(order)
   (order.status == "paid" || order.status == "ordered") && !order.cancelled?
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :require_user
  
  def show
    @user = User.find(session[:user_id])
  end
end

app/views/admin/dashboards/show.html.erb
<h1>The All-Powerful Admin Dashboard for <%= @user.username %> </h1>

<div class="container">
  <br>
  <%= link_to "Edit Admin Account", edit_admin_user_path, class: "btn btn-primary" %>
  <br><br>
</div>


<h2>All Orders</h2>

<table class="table admin_orders">
  <tr>
    <th>
      Order Number
    </th>
  </tr>
  <% @orders.each do |order| %>
    <tr>
      <td>
        <%= link_to order.id, order_path(order)%>
        <% if can_be_cancelled?(order) %>
      </td>
      <td>
        <%= link_to "cancel", order_path(order, :status => "cancelled"), method: :patch %>
        <% end %>
        <% if order.ordered? %>
      </td>
      <td>
        <%= link_to "mark as paid", order_path(order, :status => "paid"), method: :patch %>
        <% end %>
        <% if !order.ordered? && order.paid? %>
      </td>
      <td>
        <%= link_to "mark as completed", order_path(order, :status => "completed"), method: :patch %>
        <% end %>
      </td>
    </tr>
    <% end %>
</table>

<h2>Breakdown By Status</h2>
<table class="table admin_orders_status">
  <th>
    Status
  </th>
  <th>
    Amount
  </th>
  <tr>
    <td>
      <%= link_to "Ordered", admin_orders_ordered_path(:status => 0)  %>:
    </td>
    <td>
      <%= @orders.ordered.count %>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to "Paid", admin_orders_paid_path(:status => 1)  %>:
    </td>
    <td>
      <%= @orders.paid.count %>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to "Cancelled", admin_orders_cancelled_path(:status => 2)  %>:
    </td>
    <td>
      <%= @orders.cancelled.count %>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to "Completed", admin_orders_completed_path(:status => 3)  %>:
    </td>
    <td>
      <%= @orders.completed.count %>
    </td>
  </tr>
</table>

<%= link_to "Create an Item", new_item_path %>